<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWDVqDHr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWDVqDHr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWDVqDHr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWDVqDHr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWDVqDHr\App_KernelDevDebugContainer([
    'container.build_hash' => 'WDVqDHr',
    'container.build_id' => 'dc323e30',
    'container.build_time' => 1776619656,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWDVqDHr');
