<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEnzPMQv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEnzPMQv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEnzPMQv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEnzPMQv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEnzPMQv\App_KernelDevDebugContainer([
    'container.build_hash' => 'EnzPMQv',
    'container.build_id' => 'd45a43e8',
    'container.build_time' => 1776441322,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEnzPMQv');
